- name:  Create SSH key to trust on whole infrastructure
  hosts: localhost
  vars_files:
    - variables.yaml
    - vault-variables.yaml
    - bm-ansible-nodes.json
  tasks:
  - name: Generate id_rsa key
    openssh_keypair:
      path: "{{ ssh_key }}"
      type: rsa
      size: 4096
      state: present
      force: no
