apiVersion: v1
baseDomain: {{ base_domain }}
metadata:
  name: {{ cluster_name }}
networking:
  machineNetwork:
  - cidr: {{ baremetal_net.net }}/{{ baremetal_net.prefix }}
  networkType: OpenShiftSDN
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: {{ vip.api }}
    ingressVIP: {{ vip.apps }}
    bootstrapOSImage: BOOTSTRAPOSIMAGE
    provisioningNetworkCIDR: {{ provision_net.net }}/{{ provision_net.prefix }}
    provisioningNetworkInterface: {{ provision_net.net_interface }}
    provisioningBridge: "provisioning"
    provisioningDHCPRange: {{ provision_net.dhcp_start }},{{ provision_net.dhcp_end }}
    provisioningNetwork: Managed
    #bootstrapProvisioningIP: 192.168.201.51
    externalBridge: "baremetal"
    hosts:
{% for host in master_nodes %}
{% if host != 'localhost' %}
      - name: {{ host.name }}
        role: master
        bmc:
          address: ipmi://{{ host.vbmc_ip }}:{{ host.vbmc_port }}
          username: admin
          password: {{ secure_password }}
        bootMACAddress: {{ host.provisioning_mac }}
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
        #hardwareProfile: default
{% endif %}
{% endfor %}
{% for host in worker_nodes %}
{% if host != 'localhost' %}
      - name: {{ host.name }}
        role: worker
        bmc:
          address: ipmi://{{ host.vbmc_ip }}:{{ host.vbmc_port }}
          username: admin
          password: {{ secure_password }}
        bootMACAddress: {{ host.provisioning_mac }}
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
        #hardwareProfile: default
{% endif %}
{% endfor %}
