apiVersion: v1
baseDomain: example.com
metadata:
  name: ocp4-lab
networking:
  machineNetwork:
  - cidr: 192.168.203.0/24
  networkType: OpenShiftSDN
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.203.80
    ingressVIP: 192.168.203.81
    bootstrapOSImage: BOOTSTRAPOSIMAGE
    provisioningNetworkCIDR: 192.168.201.0/24
    provisioningNetworkInterface: enp1s0
    provisioningBridge: "provisioning"
    provisioningDHCPRange: 192.168.201.140,192.168.201.160
    provisioningNetwork: Managed
    bootstrapProvisioningIP: 192.168.201.51
    externalBridge: "baremetal"
    hosts:
      - name: master-0
        role: master
        bmc:
          address: ipmi://192.168.201.102
          username: admin
          password: redhat
        bootMACAddress: 52:54:00:00:32:00
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
        #hardwareProfile: default
      - name: master-1
        role: master
        bmc:
          address: ipmi://192.168.201.103
          username: admin
          password: redhat
        bootMACAddress: 52:54:00:00:32:01
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
        #hardwareProfile: default
      - name: master-2
        role: master
        bmc:
          address: ipmi://192.168.201.104
          username: admin
          password: redhat
        bootMACAddress: 52:54:00:00:32:02
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
        #hardwareProfile: default
      - name: worker-0
        role: worker
        bmc:
          address: ipmi://192.168.201.13
          username: admin
          password: redhat
        bootMACAddress: 52:54:00:00:32:03
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
        #hardwareProfile: default
      - name: worker-1
        role: worker
        bmc:
          address: ipmi://192.168.201.14
          username: admin
          password: redhat
        bootMACAddress: 52:54:00:00:32:04
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
        #hardwareProfile: default
      - name: worker-2
        role: worker
        bmc:
          address: ipmi://192.168.201.117
          username: admin
          password: redhat
        bootMACAddress: 52:54:00:00:32:05
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
      #  hardwareProfile: default
