apiVersion: v1
baseDomain: {{ base_domain }}
metadata:
  name: {{ cluster_name }}
networking:
  machineNetwork:
  - cidr: {{ baremetal_net.net }}/{{ baremetal_net.prefix }}
  networkType: OpenShiftSDN
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: {{ vip.api }}
    ingressVIP: {{ vip.apps }}
    bootstrapOSImage: BOOTSTRAPOSIMAGE
{% if redfish.enable == True  %}
    provisioningNetwork: Disabled
{% else %}
    provisioningNetworkCIDR: {{ provision_net.net }}/{{ provision_net.prefix }}
    provisioningNetworkInterface: {{ provision_net.net_interface }}
    provisioningBridge: "provisioning"
    provisioningDHCPRange: {{ provision_net.dhcp_start }},{{ provision_net.dhcp_end }}
    provisioningNetwork: Managed
{% endif %}
    externalBridge: "baremetal"
    hosts:
{% for host in master_nodes %}
{% if host != 'localhost' %}
      - name: {{ host.name }}
        role: master
        bmc:
{% if redfish.enable == True  %}
          address: redfish-virtualmedia://{{ host.redfish_ip }}:{{ host.redfish_port }}/redfish/v1/Systems/{{ host.name }}
          disableCertificateVerification: True
{% else %}
          address: ipmi://{{ host.vbmc_ip }}:{{ host.vbmc_port }}
{% endif %}
          username: admin
          password: {{ secure_password }}
{% if redfish.enable == True  %}
        bootMACAddress: {{ host.baremetal_mac }}
{% else %}
        bootMACAddress: {{ host.provisioning_mac }}
{% endif %}
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
{% endif %}
{% endfor %}
{% for host in worker_nodes %}
{% if host != 'localhost' %}
      - name: {{ host.name }}
        role: worker
        bmc:
{% if redfish.enable == True  %}
          address: redfish-virtualmedia://{{ host.redfish_ip }}:{{ host.redfish_port }}/redfish/v1/Systems/{{ host.name }}
          disableCertificateVerification: True
{% else %}
          address: ipmi://{{ host.vbmc_ip }}:{{ host.vbmc_port }}
{% endif %}
          username: admin
          password: {{ secure_password }}
{% if redfish.enable == True  %}
        bootMACAddress: {{ host.baremetal_mac }}
{% else %}
        bootMACAddress: {{ host.provisioning_mac }}
{% endif %}
        rootDeviceHints:
         deviceName: "/dev/vda"
        bootMode: legacy
{% endif %}
{% endfor %}
